added entry to Monday, April 22
dgwyn/dgwyn.github.io pull request #2
Opened 2019-04-23 05:04 UTC by dgwyn

could you please check for errors?

2019-04-23 05:06 UTC, hanafina approved these changes

2019-04-23 06:31 UTC, ghost requested changes

2019-04-23 06:31 UTC, defn commented on index.md
> +kick the ball to help him. ususally, I would tell him to stop, but I didn't
Fix capitalization, spelling of `ususally`

2019-04-23 06:31 UTC, defn commented on index.md
> +beat him i was very sweaty. But I was very happy.
Rephrase `but when beat him`.  Fix capitalization.

2019-04-25 01:51 UTC, ghost approved these changes

2019-04-25 01:51 UTC, merged